name: Docker-Downloader
on: [workflow_dispatch] # 手动触发开关
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save
        run: |
          docker pull tailscale/tailscale:latest
          docker save tailscale/tailscale:latest > tailscale.tar
      - name: Upload to Cloud
        uses: actions/upload-artifact@v4
        with:
          name: my-image
          path: tailscale.tar
