name: Docker-Downloader
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull ARM64 Image
        run: |
          # 核心修正：加入 --platform linux/arm64 开关
          docker pull --platform linux/arm64 tailscale/tailscale:latest
          docker save tailscale/tailscale:latest > tailscale_arm64.tar
      - name: Upload to Cloud
        uses: actions/upload-artifact@v4
        with:
          name: my-arm64-image
          path: tailscale_arm64.tar
